from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from execraft.browser.adapter import (
    BrowserAdapter,
    ExecuteResult,
    PrepareResult,
    ProbeResult,
    RunStatus,
)


class FakeBrowserAdapter(BrowserAdapter):
    """Fake browser adapter for testing — simulates all operations without a real browser."""

    def __init__(
        self,
        *,
        fail_login: bool = False,
        fail_execute: bool = False,
        repo_prefix: str = "myrepo",
        state_dir: Path | None = None,
    ) -> None:
        self._runs: dict[str, dict[str, Any]] = {}
        self._fail_login = fail_login
        self._fail_execute = fail_execute
        self._repo_prefix = repo_prefix
        self._state_dir = state_dir
        if self._state_dir is not None:
            self._state_dir.mkdir(parents=True, exist_ok=True)

    def _state_path(self, run_id: str) -> Path | None:
        return self._state_dir / f"{run_id}.json" if self._state_dir else None

    def _save(self, run_id: str, run: dict[str, Any]) -> None:
        self._runs[run_id] = run
        path = self._state_path(run_id)
        if path is not None:
            path.write_text(json.dumps(run, indent=2) + "\n", encoding="utf-8")

    def _load(self, run_id: str) -> dict[str, Any] | None:
        if run_id in self._runs:
            return self._runs[run_id]
        path = self._state_path(run_id)
        if path is not None and path.is_file():
            value = json.loads(path.read_text(encoding="utf-8"))
            self._runs[run_id] = value
            return value
        return None

    async def login(self, profile_dir: Path | None = None) -> dict[str, Any]:
        if self._fail_login:
            msg = "Simulated login failure"
            raise RuntimeError(msg)
        return {"authenticated": True, "profile": str(profile_dir) if profile_dir else None}

    async def probe(self) -> ProbeResult:
        return ProbeResult(available=True, browser_version="fake/1.0", message="Fake adapter ready")

    async def prepare(
        self, archive_path: Path, bundle_manifest: dict[str, Any]
    ) -> PrepareResult:
        run_id = str(bundle_manifest.get("run_id", ""))
        if not run_id:
            import uuid

            run_id = str(uuid.uuid4())
        self._save(run_id, {
            "state": "prepared",
            "archive_path": str(archive_path),
            "bundle_manifest": bundle_manifest,
        })
        return PrepareResult(run_id=run_id, archive_path=archive_path, bundle_manifest=bundle_manifest)

    async def execute(self, run_id: str) -> ExecuteResult:
        if self._fail_execute:
            msg = "Simulated execute failure"
            raise RuntimeError(msg)

        run = self._load(run_id)
        if run is None:
            return ExecuteResult(run_id=run_id, success=False, message="Run not found")

        repository_ids = list((run.get("bundle_manifest", {}).get("repos") or {}).keys())
        repo_prefix = repository_ids[0] if repository_ids else self._repo_prefix
        created: list[dict[str, Any]] = [
            {
                "path": f"{repo_prefix}/test_file.md",
                "content": "# Test\n\nGenerated by fake adapter.\n",
                "action": "create",
            }
        ]
        run["state"] = "completed"
        run["changed_files"] = created
        self._save(run_id, run)
        return ExecuteResult(
            run_id=run_id,
            success=True,
            changed_files=created,
            message="Fake execution completed",
        )

    async def status(self, run_id: str) -> RunStatus:
        run = self._load(run_id)
        if run is None:
            return RunStatus(run_id=run_id, state="failed", message="Run not found")
        return RunStatus(run_id=run_id, state=run["state"], message="Fake status")
