"""Project descriptor discovery, validation, and local path bindings.

Project descriptors contain portable logical topology. Host-specific checkout paths live
outside the repository in an XDG configuration binding and are never committed.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path, PurePosixPath
from typing import Any, Iterable, Mapping

import yaml

from execraft.control_plane import default_control_root, xdg_config_home
from execraft.persistence.atomic import atomic_write_yaml


class ProjectError(RuntimeError):
    """Raised when a project descriptor or local binding is missing or unsafe."""


class ProjectNotFoundError(ProjectError):
    """Raised when no project can be resolved for an otherwise valid lookup."""


def validate_project_id(project_id: str) -> str:
    """Validate a project identifier before using it in host-local paths."""

    value = str(project_id).strip()
    if not value or not value.replace("-", "_").isidentifier():
        raise ProjectError(f"invalid project id: {value!r}")
    return value


RESERVED_WORKSPACE_NAMES = {
    ".execraft",
    ".vscode",
    ".agents",
    ".claude",
    ".codex",
    ".gemini",
    ".opencode",
    "AGENTS.md",
    "CLAUDE.md",
    "opencode.json",
}

_PROJECT_PATH_KEYS = (
    "task_templates",
    "instructions_dir",
    "skills_dir",
    "opencode_dir",
    "claude_dir",
    "codex_dir",
    "vscode_dir",
    "policies_dir",
    "verification_file",
    "agents_file",
    "resources_file",
    "provenance_file",
    "devcontainer_dir",
)


@dataclass(frozen=True)
class ProjectRepository:
    id: str
    path: str
    role: str = "component"
    required: bool = True
    base_branch: str = "main"
    workspace_name: str = ""
    mutability: str = "task_owned"


@dataclass(frozen=True)
class ProjectDescriptor:
    id: str
    directory: Path
    description: str = ""
    repositories: tuple[ProjectRepository, ...] = ()
    default_policy: str = "workspace-write"
    paths: Mapping[str, str] = field(default_factory=dict)
    editor: Mapping[str, Any] = field(default_factory=dict)
    policy_profiles: tuple[str, ...] = ()
    capabilities: tuple[str, ...] = ()
    path_base: str = "registry_root"
    profile: str = ""
    features: tuple[str, ...] = ()
    generated_with: str = ""

    def repository(self, repository_id: str) -> ProjectRepository:
        for repository in self.repositories:
            if repository.id == repository_id:
                return repository
        raise ProjectError(
            f"project {self.id!r} has no repository {repository_id!r}"
        )

    @property
    def path_root(self) -> Path:
        """Return the root used by portable project configuration paths.

        Legacy descriptors resolve paths from the Execraft checkout root.  New
        descriptors generated by the bootstrapper are self-contained and
        resolve them from their own project directory, which makes ``--output``
        truthful and allows descriptors to be validated outside this checkout.
        """

        if self.path_base == "project_directory":
            return self.directory
        return _repository_root_for_descriptor(self.directory)

    def configured_path(self, key: str, default: str = "") -> Path | None:
        relative = str(self.paths.get(key, default) or "").strip()
        return (self.path_root / relative).resolve() if relative else None


@dataclass(frozen=True)
class ProjectBinding:
    project_id: str
    source_root: Path


@dataclass(frozen=True)
class ProjectRegistration:
    """Host-local route to a portable project descriptor and source checkout."""

    project_id: str
    descriptor: Path | None = None
    source_root: Path | None = None


@dataclass(frozen=True)
class ProjectCatalogEntry:
    """One resolved project plus the route used to discover it."""

    project: ProjectDescriptor
    origin: str
    registration: ProjectRegistration | None = None


def _safe_relative_path(value: object, *, label: str, allow_dot: bool = False) -> str:
    text = str(value or "").strip()
    if not text:
        raise ProjectError(f"{label} cannot be empty")
    path = PurePosixPath(text)
    if path.is_absolute() or ".." in path.parts:
        raise ProjectError(f"{label} must be a safe relative path: {text!r}")
    normalized = path.as_posix()
    if normalized == "." and not allow_dot:
        raise ProjectError(f"{label} cannot be '.'")
    return normalized


def _repository_root_for_descriptor(project_dir: Path) -> Path:
    # Registered projects live at <Execraft>/projects/<id>. Keeping this helper in
    # one place makes path validation explicit and avoids caller-specific guesses.
    return project_dir.resolve().parent.parent


def load_project(project_dir: Path) -> ProjectDescriptor:
    """Load and validate one portable ``project.yaml`` descriptor."""

    project_dir = project_dir.resolve()
    project_file = project_dir / "project.yaml"
    if not project_file.is_file():
        raise ProjectError(f"project.yaml not found in {project_dir}")
    try:
        raw = yaml.safe_load(project_file.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError as exc:
        raise ProjectError(f"invalid YAML in {project_file}: {exc}") from exc
    if not isinstance(raw, Mapping):
        raise ProjectError(f"project.yaml must contain a mapping: {project_file}")
    schema_version = int(raw.get("schema_version", 0))
    if schema_version not in {1, 2, 3}:
        raise ProjectError(f"unsupported project schema_version: {schema_version!r}")
    project_id = validate_project_id(str(raw.get("project", "")))

    repositories_raw = raw.get("repositories") or []
    if not isinstance(repositories_raw, list) or not repositories_raw:
        raise ProjectError("project repositories must be a non-empty list")
    repositories: list[ProjectRepository] = []
    seen_ids: set[str] = set()
    seen_paths: set[str] = set()
    seen_workspace_names: set[str] = set()
    for item in repositories_raw:
        if not isinstance(item, Mapping):
            raise ProjectError("each project repository must be a mapping")
        repository_id = str(item.get("id", "")).strip()
        if not repository_id or not repository_id.replace("-", "_").isidentifier():
            raise ProjectError(f"invalid repository id: {repository_id!r}")
        if repository_id in seen_ids:
            raise ProjectError(f"duplicate repository id: {repository_id}")
        path = _safe_relative_path(
            item.get("path"), label=f"repository {repository_id} path", allow_dot=True
        )
        if path in seen_paths:
            raise ProjectError(f"duplicate repository path: {path}")
        base_branch = str(item.get("base_branch", "main")).strip()
        if not base_branch:
            raise ProjectError(f"repository {repository_id} base_branch cannot be empty")
        workspace_name = _safe_relative_path(
            item.get("workspace_name", repository_id),
            label=f"repository {repository_id} workspace_name",
        )
        workspace_path = PurePosixPath(workspace_name)
        if workspace_path.parts[0] in RESERVED_WORKSPACE_NAMES:
            raise ProjectError(
                f"repository {repository_id} workspace_name collides with generated state: "
                f"{workspace_name!r}"
            )
        for previous in seen_workspace_names:
            previous_path = PurePosixPath(previous)
            if (
                workspace_path == previous_path
                or previous_path in workspace_path.parents
                or workspace_path in previous_path.parents
            ):
                raise ProjectError(
                    "overlapping repository workspace_name values: "
                    f"{previous!r} and {workspace_name!r}"
                )
        mutability = str(item.get("mutability", "task_owned")).strip()
        if mutability not in {"task_owned", "runtime_only"}:
            raise ProjectError(
                f"repository {repository_id} mutability must be task_owned or runtime_only"
            )
        repositories.append(
            ProjectRepository(
                id=repository_id,
                path=path,
                role=str(item.get("role", "component")).strip() or "component",
                required=bool(item.get("required", True)),
                base_branch=base_branch,
                workspace_name=workspace_name,
                mutability=mutability,
            )
        )
        seen_ids.add(repository_id)
        seen_paths.add(path)
        seen_workspace_names.add(workspace_name)

    path_base = str(raw.get("path_base", "registry_root")).strip()
    if path_base not in {"registry_root", "project_directory"}:
        raise ProjectError(
            "path_base must be 'registry_root' or 'project_directory'"
        )

    configured_paths: dict[str, str] = {}
    for key in _PROJECT_PATH_KEYS:
        if raw.get(key):
            configured_paths[key] = _safe_relative_path(raw[key], label=key)
    repository_root = (
        project_dir
        if path_base == "project_directory"
        else _repository_root_for_descriptor(project_dir)
    )
    for key, relative in configured_paths.items():
        candidate = repository_root / relative
        if key.endswith("_file"):
            if not candidate.is_file():
                raise ProjectError(f"{key} file does not exist: {relative}")
        elif not candidate.is_dir():
            raise ProjectError(f"{key} directory does not exist: {relative}")

    policy_profiles = raw.get("policy_profiles") or {}
    if not isinstance(policy_profiles, Mapping):
        raise ProjectError("policy_profiles must be a mapping")
    default_policy = str(raw.get("default_policy", "workspace-write")).strip()
    if policy_profiles and default_policy not in policy_profiles:
        raise ProjectError(
            f"default_policy {default_policy!r} is not declared in policy_profiles"
        )
    policies_dir = configured_paths.get("policies_dir")
    if policy_profiles and policies_dir:
        for profile_id in policy_profiles:
            policy_file = repository_root / policies_dir / f"{profile_id}.yaml"
            if not policy_file.is_file():
                raise ProjectError(
                    f"policy profile {profile_id!r} has no definition: {policy_file}"
                )

    editor = raw.get("editor") or {}
    if not isinstance(editor, Mapping):
        raise ProjectError("editor must be a mapping")
    raw_capabilities = raw.get("capabilities") or []
    if not isinstance(raw_capabilities, list) or not all(
        isinstance(item, str) and item.strip() for item in raw_capabilities
    ):
        raise ProjectError("capabilities must be a list of non-empty strings")
    raw_features = raw.get("features") or []
    if not isinstance(raw_features, list) or not all(
        isinstance(item, str) and item.strip() for item in raw_features
    ):
        raise ProjectError("features must be a list of non-empty strings")
    profile = str(raw.get("profile", "")).strip()
    if schema_version >= 3 and not profile:
        raise ProjectError("schema_version 3 projects must declare a profile")

    return ProjectDescriptor(
        id=project_id,
        directory=project_dir,
        description=str(raw.get("description", "")).strip(),
        repositories=tuple(repositories),
        default_policy=default_policy,
        paths=configured_paths,
        editor=dict(editor),
        policy_profiles=tuple(str(item) for item in policy_profiles),
        capabilities=tuple(str(item).strip() for item in raw_capabilities),
        path_base=path_base,
        profile=profile,
        features=tuple(str(item).strip() for item in raw_features),
        generated_with=str(raw.get("generated_with", "")).strip(),
    )


def config_home() -> Path:
    """Return the host-local Execraft configuration directory.

    Kept here as a compatibility facade for callers that historically imported
    it from :mod:`execraft.project`.
    """

    return xdg_config_home()


def project_binding_path(project_id: str) -> Path:
    return config_home() / "projects" / f"{validate_project_id(project_id)}.yaml"


def _registration_from_mapping(
    project_id: str, raw: Mapping[str, Any], *, path: Path
) -> ProjectRegistration:
    try:
        schema_version = int(raw.get("schema_version", 0))
    except (TypeError, ValueError) as exc:
        raise ProjectError(f"invalid project registration schema in {path}") from exc
    if schema_version not in {1, 2}:
        raise ProjectError(f"invalid project registration schema: {path}")
    if str(raw.get("project", "")).strip() != project_id:
        raise ProjectError(f"project registration ID mismatch in {path}")

    descriptor: Path | None = None
    if schema_version >= 2 and str(raw.get("descriptor", "")).strip():
        descriptor = Path(str(raw["descriptor"])).expanduser()
        if not descriptor.is_absolute():
            raise ProjectError(
                f"project registration descriptor must be absolute: {path}"
            )
        descriptor = descriptor.resolve()

    source_root: Path | None = None
    if str(raw.get("source_root", "")).strip():
        source_root = Path(str(raw["source_root"])).expanduser()
        if not source_root.is_absolute():
            raise ProjectError(
                f"project registration source_root must be absolute: {path}"
            )
        source_root = source_root.resolve()

    return ProjectRegistration(
        project_id=project_id,
        descriptor=descriptor,
        source_root=source_root,
    )


def load_project_registration(project_id: str) -> ProjectRegistration | None:
    """Load a schema-v1 binding or schema-v2 project registration."""

    path = project_binding_path(project_id)
    if not path.is_file():
        return None
    try:
        raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError as exc:
        raise ProjectError(f"invalid project registration {path}: {exc}") from exc
    if not isinstance(raw, Mapping):
        raise ProjectError(f"project registration must contain a mapping: {path}")
    return _registration_from_mapping(project_id, raw, path=path)


def iter_project_registrations() -> Iterable[ProjectRegistration]:
    """Yield all host-local registrations in stable project-ID order."""

    directory = config_home() / "projects"
    if not directory.is_dir():
        return
    for path in sorted(directory.glob("*.yaml")):
        project_id = path.stem
        registration = load_project_registration(project_id)
        if registration is not None:
            yield registration


def _write_project_registration(registration: ProjectRegistration) -> Path:
    path = project_binding_path(registration.project_id)
    path.parent.mkdir(parents=True, exist_ok=True)
    payload: dict[str, Any] = {
        "schema_version": 2,
        "project": registration.project_id,
    }
    if registration.descriptor is not None:
        payload["descriptor"] = str(registration.descriptor.resolve())
    if registration.source_root is not None:
        payload["source_root"] = str(registration.source_root.resolve())
    atomic_write_yaml(path, payload, sort_keys=False)
    return path


def remove_project_registration(project_id: str) -> ProjectRegistration | None:
    """Remove and return one host-local project registration.

    Project descriptors are portable data and are never deleted by this
    operation.  The helper only removes the host-local route in the XDG config
    directory, which makes it suitable for reversible catalog operations.
    """

    registration = load_project_registration(project_id)
    if registration is None:
        return None
    project_binding_path(project_id).unlink(missing_ok=True)
    return registration


def register_project_descriptor(
    descriptor: Path,
    *,
    source_root: Path | None = None,
    replace: bool = False,
) -> Path:
    """Register an arbitrary portable descriptor without copying it.

    ``descriptor`` may name either ``project.yaml`` or its containing project
    directory.  Existing source bindings are preserved.  A conflicting route
    is rejected unless ``replace`` is requested explicitly by migration code.
    """

    candidate = descriptor.expanduser().resolve()
    project_dir = candidate if candidate.is_dir() else candidate.parent
    project = load_project(project_dir)
    project_file = project.directory / "project.yaml"
    existing = load_project_registration(project.id)
    if (
        existing is not None
        and existing.descriptor is not None
        and existing.descriptor != project_file
        and not replace
    ):
        raise ProjectError(
            f"project {project.id!r} is already registered at "
            f"{existing.descriptor}; refusing conflicting descriptor {project_file}"
        )
    resolved_source = (
        source_root.expanduser().resolve()
        if source_root is not None
        else (existing.source_root if existing is not None else None)
    )
    if resolved_source is not None and not resolved_source.is_dir():
        raise ProjectError(f"project source root does not exist: {resolved_source}")
    return _write_project_registration(
        ProjectRegistration(
            project_id=project.id,
            descriptor=project_file,
            source_root=resolved_source,
        )
    )


def write_project_binding(
    project_id: str,
    source_root: Path,
    *,
    descriptor: Path | None = None,
) -> Path:
    """Create or update the source route while preserving descriptor metadata."""

    source_root = source_root.expanduser().resolve()
    if not source_root.is_dir():
        raise ProjectError(f"project source root does not exist: {source_root}")
    existing = load_project_registration(project_id)
    descriptor_path = descriptor.expanduser().resolve() if descriptor else None
    if descriptor_path is None and existing is not None:
        descriptor_path = existing.descriptor
    if descriptor_path is not None:
        descriptor_project = load_project(
            descriptor_path if descriptor_path.is_dir() else descriptor_path.parent
        )
        if descriptor_project.id != project_id:
            raise ProjectError(
                f"descriptor project {descriptor_project.id!r} does not match "
                f"binding project {project_id!r}"
            )
        descriptor_path = descriptor_project.directory / "project.yaml"
    return _write_project_registration(
        ProjectRegistration(
            project_id=project_id,
            descriptor=descriptor_path,
            source_root=source_root,
        )
    )


def load_project_binding(project_id: str) -> ProjectBinding | None:
    registration = load_project_registration(project_id)
    if registration is None or registration.source_root is None:
        return None
    return ProjectBinding(
        project_id=registration.project_id,
        source_root=registration.source_root,
    )


def _legacy_project_directory(root: Path, project_id: str) -> Path:
    return root.expanduser().resolve() / "projects" / validate_project_id(project_id)


def _uses_host_project_registry(root: Path) -> bool:
    """Return whether *root* is the active host control-plane home.

    Callers frequently pass temporary or fixture roots explicitly.  Mixing the
    process-wide XDG registry into those roots makes their project catalog
    depend on unrelated host state and can redirect task operations outside the
    requested control plane.
    """

    return root.expanduser().resolve() == default_control_root()


def project_directory(root: Path, project_id: str) -> Path:
    """Resolve a project directory from registration or the legacy catalog."""

    registration = (
        load_project_registration(project_id)
        if _uses_host_project_registry(root)
        else None
    )
    if registration is not None and registration.descriptor is not None:
        if not registration.descriptor.is_file():
            raise ProjectError(
                f"registered project descriptor does not exist: "
                f"{registration.descriptor}"
            )
        return registration.descriptor.parent
    return _legacy_project_directory(root, project_id)


def load_registered_project(root: Path, project_id: str) -> ProjectDescriptor:
    """Load a project from the host registry or legacy ``root/projects``."""

    directory = project_directory(root, project_id)
    if not (directory / "project.yaml").is_file():
        raise ProjectError(
            f"project {project_id!r} is not registered and no legacy descriptor "
            f"exists at {directory / 'project.yaml'}"
        )
    project = load_project(directory)
    if project.id != project_id:
        raise ProjectError(
            f"registered project ID mismatch: expected {project_id!r}, "
            f"descriptor contains {project.id!r}"
        )
    return project


def list_project_catalog(
    root: Path, *, skip_invalid: bool = False
) -> list[ProjectCatalogEntry]:
    """Return registered and legacy projects, de-duplicated by project ID.

    Explicit registrations take precedence over a same-ID legacy directory.
    This makes migration non-destructive: descriptors can stay in an older
    checkout while the installed CLI resolves them from any working directory.
    """

    result: dict[str, ProjectCatalogEntry] = {}
    projects_root = root.expanduser().resolve() / "projects"
    if projects_root.is_dir():
        for child in sorted(projects_root.iterdir()):
            if child.is_dir() and (child / "project.yaml").is_file():
                try:
                    project = load_project(child)
                except ProjectError:
                    if skip_invalid:
                        continue
                    raise
                registration = load_project_registration(project.id)
                result[project.id] = ProjectCatalogEntry(
                    project=project,
                    origin="control_root",
                    registration=registration,
                )

    registrations = (
        iter_project_registrations() if _uses_host_project_registry(root) else ()
    )
    for registration in registrations:
        if registration is None or registration.descriptor is None:
            continue
        if not registration.descriptor.is_file():
            if skip_invalid:
                continue
            raise ProjectError(
                f"registered project descriptor does not exist: "
                f"{registration.descriptor}"
            )
        try:
            project = load_project(registration.descriptor.parent)
        except ProjectError:
            if skip_invalid:
                continue
            raise
        if project.id != registration.project_id:
            raise ProjectError(
                f"project registration {registration.project_id!r} points to "
                f"descriptor for {project.id!r}"
            )
        result[project.id] = ProjectCatalogEntry(
            project=project,
            origin="registry",
            registration=registration,
        )
    return [result[key] for key in sorted(result)]


def list_projects(root: Path) -> list[ProjectDescriptor]:
    return [entry.project for entry in list_project_catalog(root)]


def _contains(path: Path, candidate: Path) -> bool:
    try:
        candidate.resolve().relative_to(path.resolve())
    except ValueError:
        return False
    return True


def resolve_current_project(
    root: Path,
    *,
    project_id: str | None = None,
    cwd: Path | None = None,
) -> ProjectDescriptor:
    """Resolve an explicit project or infer it from descriptor/source ancestry."""

    if project_id:
        return load_registered_project(root, project_id)

    current = (cwd or Path.cwd()).expanduser().resolve()
    direct_candidates: list[tuple[int, ProjectDescriptor]] = []
    for ancestor in (current, *current.parents):
        if (ancestor / "project.yaml").is_file():
            project = load_project(ancestor)
            direct_candidates.append((len(ancestor.parts), project))
            break

    for entry in list_project_catalog(root):
        project = entry.project
        if _contains(project.directory, current):
            direct_candidates.append((len(project.directory.parts), project))
        registration = entry.registration or load_project_registration(project.id)
        if (
            registration is not None
            and registration.source_root is not None
            and _contains(registration.source_root, current)
        ):
            direct_candidates.append(
                (len(registration.source_root.parts), project)
            )

    if not direct_candidates:
        raise ProjectNotFoundError(
            f"cannot infer a registered project from {current}; pass --project or "
            "run 'execraft init' from the project source tree"
        )
    direct_candidates.sort(key=lambda item: item[0], reverse=True)
    best_depth = direct_candidates[0][0]
    best: dict[str, ProjectDescriptor] = {
        project.id: project
        for depth, project in direct_candidates
        if depth == best_depth
    }
    if len(best) != 1:
        raise ProjectError(
            "current directory matches multiple projects: "
            + ", ".join(sorted(best))
            + "; pass --project"
        )
    return next(iter(best.values()))


def resolve_project_source_root(
    project: ProjectDescriptor, explicit: Path | None = None
) -> Path:
    if explicit is not None:
        root = explicit.expanduser().resolve()
    else:
        binding = load_project_binding(project.id)
        if binding is None:
            raise ProjectError(
                f"project {project.id!r} has no local source-root binding; run "
                f"'execraft project bind {project.id} --source /path/to/checkouts'"
            )
        root = binding.source_root
    if not root.is_dir():
        raise ProjectError(f"project source root does not exist: {root}")
    return root


def validate_task_against_project(manifest: Any, project: ProjectDescriptor) -> None:
    """Enforce the project catalog as the ownership floor for a task manifest."""

    if manifest.project != project.id:
        raise ProjectError(
            f"task project {manifest.project!r} does not match catalog {project.id!r}"
        )
    catalog = {repository.id: repository for repository in project.repositories}
    task = {repository.id: repository for repository in manifest.repositories}
    unknown = sorted(set(task) - set(catalog))
    if unknown:
        raise ProjectError(
            "task contains repositories absent from the project catalog: "
            + ", ".join(unknown)
        )
    missing = sorted(
        repository_id
        for repository_id, repository in catalog.items()
        if repository.required and repository_id not in task
    )
    if missing:
        raise ProjectError(
            "task omits required project repositories: " + ", ".join(missing)
        )
    for repository_id, task_repository in task.items():
        project_repository = catalog[repository_id]
        if project_repository.required and not task_repository.required:
            raise ProjectError(
                f"task weakens required repository {repository_id!r} to optional"
            )
        if task_repository.role != project_repository.role:
            raise ProjectError(
                f"task role for {repository_id!r} is {task_repository.role!r}; "
                f"project catalog requires {project_repository.role!r}"
            )
        if (
            project_repository.mutability == "runtime_only"
            and task_repository.mutability != "runtime_only"
        ):
            raise ProjectError(
                f"task makes catalog runtime-only repository {repository_id!r} writable"
            )
