"""Orchestration layer for project-agnostic deterministic work-package execution."""

from .agent_console import InteractiveTerminalPolicy
from .artifacts import AgentArtifactReference, AgentArtifactStore
from .checkpoints import StateCheckpoint, StateCheckpointStore
from .context_budget import (
    ContextBlock,
    ContextBudgetError,
    ContextPlanner,
    DEFAULT_TOKEN_BUDGETS,
    PlannedContext,
    TokenBudget,
    budgets_from_mapping,
    estimate_tokens,
)
from .context_capsule import (
    ContextCapsuleError,
    PackageContextCapsule,
    PackageContextCapsuleStore,
)
from .daemon import DaemonConfig, DaemonResult, run_until_terminal
from .execution_trace import build_execution_trace, trace_scope_packages
from .execution_policy import (
    EXECUTION_ROLES,
    ROLE_BY_ID,
    ExecutionPolicyError,
    ExecutionRoleDefinition,
    effective_skill_ids,
    execution_policy_mapping,
    execution_role_metadata,
    normalize_ranked_ids,
    normalize_role_mapping,
    role_definition,
    role_for_capability,
)
from .identity import (
    OrchestrationStorageIdentity,
    namespaced_storage_key,
    resolve_storage_identity,
)
from .invocations import AgentInvocationRecord, AgentInvocationStore, handoff_sha256
from .journal import EventJournal, JournalEntry
from .models import (
    AcceptanceCriterion,
    OrchestrateError,
    PlanGraph,
    TaskExecutionState,
    TaskExecutionStateRecord,
    WorkPackage,
    WorkPackageStage,
    utc_now,
    validate_task_execution_transition,
    validate_stage_transition,
)
from .operator_acceptance import (
    ELIGIBLE_OPERATOR_ACCEPTANCE_STAGES,
    accepted_criterion_ids,
    operator_acceptance_eligibility,
    operator_acceptance_preview,
)
from .package_finalization import (
    AggregateFinalizationAssessment,
    ChildFinalizationEvidence,
    WorkspaceFinalizationPolicy,
    assess_aggregate_children,
    qualify_dirty_paths,
    workspace_finalization_policy_from_scheduling,
)
from .normalizer import (
    NormalizationReport,
    load_plan_graph_file,
    normalize_work_packages,
    parse_plan_document,
    plan_graph_from_mapping,
)
from .orchestrator import OrchestrationConfig, ProjectOrchestrator
from .progress import HumanProgressReporter
from .provider_failover import (
    FailoverOutcome,
    ProviderFailoverCoordinator,
    ProviderFailoverStrategy,
)
from .execution_health import ExecutionHealth, ExecutionHealthStore
from .provider_health import ProviderHealth, ProviderHealthStore
from .provider_promotion import (
    ProviderPromotion,
    ProviderPromotionStore,
    parse_promotion_duration,
)
from .resource import ResourceManager, ResourcePolicy
from .recovery_playbook import (
    RecoveryPlaybookConfigError,
    RecoveryPlaybookPolicy,
    ReviewExhaustedPlaybookPolicy,
    findings_fingerprint,
    indexed_findings,
    normalize_findings,
    recovery_playbook_policy_from_scheduling,
)
from .scheduler import (
    AgentAdapter,
    AgentAdapterCapabilities,
    AgentCapability,
    AgentExecutionError,
    AgentSchedule,
    Availability,
    StructuredHandoff,
    agent_adapter_capabilities,
    select_agent,
)
from .scope_policy import (
    ScopePathAssessment,
    ScopePolicy,
    ScopeRecoveryPolicy,
    scope_recovery_policy_from_scheduling,
)
from .supervisor import (
    HumanDecisionOption,
    HumanDecisionRequest,
    HumanDecisionRisk,
    IncidentClass,
    IncidentStatus,
    SupervisorAutoDecisionEvaluation,
    SupervisorAutoDecisionPolicy,
    SupervisorConfigError,
    SupervisorDecision,
    SupervisorDecisionKind,
    SupervisorDelegation,
    SupervisorIncident,
    SupervisorIncidentStore,
    SupervisorPolicy,
    classify_incident,
    evaluate_supervisor_auto_decision,
    is_recoverable_prompt_transport_failure,
    unfinished_supervisor_delegations,
    supervisor_output_schema,
)
from .task_status import RuntimeStatusSnapshot, sync_runtime_status
from .transactions import CommitJournal, CommitTransaction, RepositorySnapshot
from .usage import AgentUsage, normalize_agent_usage
from .verification import (
    VerificationCommand,
    VerificationProfile,
    VerificationRegistry,
    VerificationResult,
    resolve_profile,
    run_verification_command,
)

__all__ = [
    "EXECUTION_ROLES",
    "ROLE_BY_ID",
    "AcceptanceCriterion",
    "AgentAdapter",
    "AgentAdapterCapabilities",
    "AgentArtifactReference",
    "AgentArtifactStore",
    "AgentInvocationRecord",
    "AgentInvocationStore",
    "AgentCapability",
    "AgentExecutionError",
    "AgentSchedule",
    "Availability",
    "ContextBlock",
    "ContextBudgetError",
    "ContextCapsuleError",
    "ContextPlanner",
    "DEFAULT_TOKEN_BUDGETS",
    "PackageContextCapsule",
    "PackageContextCapsuleStore",
    "PlannedContext",
    "TokenBudget",
    "AgentUsage",
    "CommitJournal",
    "CommitTransaction",
    "AggregateFinalizationAssessment",
    "ChildFinalizationEvidence",
    "DaemonConfig",
    "DaemonResult",
    "EventJournal",
    "ELIGIBLE_OPERATOR_ACCEPTANCE_STAGES",
    "accepted_criterion_ids",
    "operator_acceptance_eligibility",
    "operator_acceptance_preview",
    "build_execution_trace",
    "budgets_from_mapping",
    "estimate_tokens",
    "normalize_agent_usage",
    "trace_scope_packages",
    "ExecutionPolicyError",
    "ExecutionRoleDefinition",
    "HumanProgressReporter",
    "HumanDecisionOption",
    "HumanDecisionRequest",
    "HumanDecisionRisk",
    "IncidentClass",
    "IncidentStatus",
    "SupervisorConfigError",
    "SupervisorAutoDecisionEvaluation",
    "SupervisorAutoDecisionPolicy",
    "SupervisorDecision",
    "SupervisorDecisionKind",
    "SupervisorDelegation",
    "SupervisorIncident",
    "SupervisorIncidentStore",
    "SupervisorPolicy",
    "InteractiveTerminalPolicy",
    "JournalEntry",
    "NormalizationReport",
    "OrchestrateError",
    "OrchestrationConfig",
    "OrchestrationStorageIdentity",
    "PlanGraph",
    "ProjectOrchestrator",
    "TaskExecutionState",
    "TaskExecutionStateRecord",
    "FailoverOutcome",
    "ProviderFailoverCoordinator",
    "ProviderFailoverStrategy",
    "ExecutionHealth",
    "ExecutionHealthStore",
    "ProviderHealth",
    "ProviderHealthStore",
    "ProviderPromotion",
    "ProviderPromotionStore",
    "parse_promotion_duration",
    "RepositorySnapshot",
    "ResourceManager",
    "ResourcePolicy",
    "RecoveryPlaybookConfigError",
    "RecoveryPlaybookPolicy",
    "ReviewExhaustedPlaybookPolicy",
    "RuntimeStatusSnapshot",
    "ScopePathAssessment",
    "ScopePolicy",
    "ScopeRecoveryPolicy",
    "WorkspaceFinalizationPolicy",
    "scope_recovery_policy_from_scheduling",
    "workspace_finalization_policy_from_scheduling",
    "assess_aggregate_children",
    "qualify_dirty_paths",
    "recovery_playbook_policy_from_scheduling",
    "findings_fingerprint",
    "indexed_findings",
    "normalize_findings",
    "classify_incident",
    "evaluate_supervisor_auto_decision",
    "is_recoverable_prompt_transport_failure",
    "unfinished_supervisor_delegations",
    "supervisor_output_schema",
    "StateCheckpoint",
    "StateCheckpointStore",
    "StructuredHandoff",
    "VerificationCommand",
    "VerificationProfile",
    "VerificationRegistry",
    "VerificationResult",
    "WorkPackage",
    "WorkPackageStage",
    "agent_adapter_capabilities",
    "effective_skill_ids",
    "execution_policy_mapping",
    "handoff_sha256",
    "execution_role_metadata",
    "load_plan_graph_file",
    "normalize_ranked_ids",
    "normalize_role_mapping",
    "namespaced_storage_key",
    "normalize_work_packages",
    "parse_plan_document",
    "plan_graph_from_mapping",
    "resolve_profile",
    "resolve_storage_identity",
    "role_definition",
    "role_for_capability",
    "run_until_terminal",
    "run_verification_command",
    "select_agent",
    "sync_runtime_status",
    "utc_now",
    "validate_task_execution_transition",
    "validate_stage_transition",
]
