"""Strict-but-tolerant extraction of agent JSON contracts.

Agent CLIs usually return a provider envelope whose final text is generated by
an LLM. Even when prompted to return only JSON, that text may be wrapped in a
Markdown fence or preceded by a short sentence. This module tolerates those
presentation wrappers while keeping the contract check fail-closed. Repairs are
limited to lossless, provider-neutral representations of the same declared
meaning; missing review decisions or blocking evidence are never invented.
"""

from __future__ import annotations

import json
from typing import Any, Iterable, Mapping


_CONTRACT_KEYS = frozenset(
    {
        "ok",
        "status",
        "summary",
        "verdict",
        "findings",
        "acceptance_evidence",
        "resolved_findings",
        "decision",
        "reason",
        "shards",
    }
)
_WRAPPER_KEYS = ("review", "result", "output", "response")
_REVIEW_FINDING_ALIASES = ("findions", "issues", "blocking_findings")
_APPROVED_VERDICTS = frozenset({"approved", "approve", "accepted", "pass", "passed"})
_CHANGES_REQUIRED_VERDICTS = frozenset(
    {
        "changes_required",
        "changes-required",
        "request_changes",
        "changes requested",
        "rejected",
        "reject",
    }
)


class StructuredOutputError(ValueError):
    """Raised when an agent result cannot satisfy its declared contract."""


def acceptance_evidence_output_schema() -> dict[str, Any]:
    """Return the strict wire representation for criterion evidence.

    Structured Outputs cannot express arbitrary-key objects.  The model-facing
    contract therefore uses an array while orchestration normalizes it back to
    the existing ``criterion_id -> evidence`` mapping.
    """

    return {
        "type": "array",
        "maxItems": 128,
        "items": {
            "type": "object",
            "additionalProperties": False,
            "required": ["criterion_id", "evidence"],
            "properties": {
                "criterion_id": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 256,
                },
                "evidence": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 8000,
                },
            },
        },
    }


def normalize_acceptance_evidence(value: Any) -> dict[str, str]:
    """Normalize legacy object and strict array evidence representations."""

    if value is None:
        return {}
    if isinstance(value, Mapping):
        items = value.items()
    elif isinstance(value, list) and all(isinstance(item, Mapping) for item in value):
        items = (
            (item.get("criterion_id", ""), item.get("evidence", ""))
            for item in value
        )
    else:
        return {}
    normalized: dict[str, str] = {}
    for raw_key, raw_value in items:
        key = str(raw_key).strip()
        evidence = str(raw_value).strip()
        if key and evidence and key not in normalized:
            normalized[key] = evidence
    return normalized


def review_output_schema() -> dict[str, Any]:
    """Return the single model-created review contract used by every review stage.

    Every declared property is required and the object is closed so this exact
    schema can be sent to strict Structured Outputs providers. Execution
    success belongs to the provider transport envelope, so the model contract
    deliberately has no second ``ok`` field.
    """

    return {
        "type": "object",
        "additionalProperties": False,
        "required": ["verdict", "findings", "observations", "summary"],
        "properties": {
            "verdict": {"enum": ["approved", "changes_required"]},
            "findings": {
                "type": "array",
                "items": {"type": "string", "minLength": 1},
            },
            "observations": {
                "type": "array",
                "items": {"type": "string", "minLength": 1},
            },
            "summary": {"type": "string", "minLength": 1},
        },
    }


def normalize_structured_result(
    payload: Mapping[str, Any],
    schema: Mapping[str, Any],
    *,
    candidate_texts: Iterable[str] = (),
) -> dict[str, Any]:
    """Return a detached, validated contract payload.

    Provider envelopes are copied before validation so orchestration metadata can
    never create self-referential objects.  If the envelope itself does not
    satisfy the schema, bounded textual candidates are parsed deterministically.
    The returned mapping is always independent from ``payload``.
    """

    public_payload = {
        str(key): value
        for key, value in payload.items()
        if not str(key).startswith("_execraft_")
    }
    try:
        direct_candidate = _normalize_contract_variant(public_payload, schema)
        direct_errors = validate_structured_object(direct_candidate, schema)
    except StructuredOutputError as exc:
        direct_candidate = dict(public_payload)
        direct_errors = [str(exc)]
    if not direct_errors:
        return dict(direct_candidate)

    required_keys = tuple(str(item) for item in (schema.get("required") or []))
    texts: list[str] = []
    message = public_payload.get("final_message")
    if isinstance(message, str) and message.strip():
        texts.append(message)
    raw_candidates = public_payload.get("structured_output_candidates")
    if isinstance(raw_candidates, list):
        texts.extend(
            str(item)
            for item in reversed(raw_candidates)
            if isinstance(item, str) and item.strip()
        )
    texts.extend(str(item) for item in candidate_texts if str(item).strip())

    last_parsed: dict[str, Any] | None = None
    last_errors = direct_errors
    for text in dict.fromkeys(texts):
        parsed = extract_structured_object(text, preferred_keys=required_keys)
        try:
            normalized = _normalize_contract_variant(parsed, schema)
            parsed_errors = validate_structured_object(normalized, schema)
        except StructuredOutputError as exc:
            normalized = dict(parsed) if parsed is not None else None
            parsed_errors = [str(exc)]
        if parsed is not None:
            last_parsed = normalized
            last_errors = parsed_errors
        if parsed is not None and not parsed_errors:
            return dict(normalized)

    errors = last_errors if last_parsed is not None else direct_errors
    raise StructuredOutputError("; ".join(errors[:4]))


def _normalize_contract_variant(
    payload: Mapping[str, Any] | None,
    schema: Mapping[str, Any],
) -> dict[str, Any] | None:
    if payload is None:
        return None
    detached = dict(payload)
    if _is_review_schema(schema):
        return normalize_review_payload(detached)
    if _is_scope_recovery_schema(schema):
        return _normalize_scope_recovery_payload(detached)
    if _is_implementation_schema(schema):
        return _normalize_implementation_payload(detached, schema)
    if _is_decomposition_schema(schema):
        return _normalize_decomposition_payload(detached)
    return detached


def _is_review_schema(schema: Mapping[str, Any]) -> bool:
    properties = schema.get("properties")
    if not isinstance(properties, Mapping):
        return False
    return {"verdict", "findings", "summary"}.issubset(properties)


def _is_scope_recovery_schema(schema: Mapping[str, Any]) -> bool:
    properties = schema.get("properties")
    if not isinstance(properties, Mapping):
        return False
    return {
        "status",
        "summary",
        "retain_paths",
        "discard_paths",
        "removed_paths",
    }.issubset(properties)


def _is_implementation_schema(schema: Mapping[str, Any]) -> bool:
    properties = schema.get("properties")
    if not isinstance(properties, Mapping):
        return False
    evidence = properties.get("acceptance_evidence")
    return (
        {"status", "acceptance_evidence"}.issubset(properties)
        and isinstance(evidence, Mapping)
        and evidence.get("type") == "array"
    )


def _is_decomposition_schema(schema: Mapping[str, Any]) -> bool:
    properties = schema.get("properties")
    return isinstance(properties, Mapping) and {
        "decision",
        "reason",
        "shards",
    }.issubset(properties)


def _normalize_implementation_payload(
    payload: Mapping[str, Any], schema: Mapping[str, Any]
) -> dict[str, Any]:
    """Accept the legacy evidence map while emitting the strict wire shape."""

    normalized = dict(payload)
    evidence = normalized.get("acceptance_evidence")
    if isinstance(evidence, Mapping):
        normalized["acceptance_evidence"] = [
            {"criterion_id": str(key), "evidence": str(value)}
            for key, value in evidence.items()
        ]
    if "summary" in (schema.get("required") or []) and not str(
        normalized.get("summary", "")
    ).strip():
        normalized["summary"] = str(
            normalized.get("implementation_summary", "")
        ).strip()
    return normalized


def _normalize_decomposition_payload(
    payload: Mapping[str, Any],
) -> dict[str, Any]:
    """Fill strict-schema fields that were optional in the legacy contract."""

    normalized = dict(payload)
    shards = normalized.get("shards")
    if isinstance(shards, list):
        normalized["shards"] = [
            {
                **dict(item),
                "finding_indexes": list(item.get("finding_indexes") or []),
                "read_scope": list(item.get("read_scope") or []),
                "write_scope": list(item.get("write_scope") or []),
                "conflict_keys": list(item.get("conflict_keys") or []),
                "parallel_safe": bool(item.get("parallel_safe", False)),
            }
            if isinstance(item, Mapping)
            else item
            for item in shards
        ]
    return normalized


def _normalize_scope_recovery_payload(
    payload: Mapping[str, Any],
) -> dict[str, Any]:
    """Canonicalize the bounded scope-recovery decision representation."""

    normalized = dict(payload)
    model_ok = normalized.pop("ok", None)
    if model_ok is not None and model_ok is not True:
        raise StructuredOutputError(
            "scope-recovery model-level ok must be true when present"
        )
    for key in ("retain_paths", "discard_paths", "removed_paths"):
        if normalized.get(key) is None:
            normalized[key] = []
    return normalized


def normalize_review_payload(payload: Mapping[str, Any]) -> dict[str, Any]:
    """Normalize lossless common review shapes and enforce cross-field meaning.

    Supported variants are deliberately about representation, not provider
    identity:

    * ``verdict: {decision, reason}`` is flattened;
    * structured finding objects become stable strings;
    * a single unambiguous common finding alias can repair a missing/empty
      canonical ``findings`` field;
    * common verdict spellings map to the two canonical decisions.

    A changes-required decision without non-empty findings remains invalid and
    is raised here, inside the invocation retry/failover boundary.
    """

    normalized = dict(payload)
    model_ok = normalized.pop("ok", None)
    if model_ok is not None and model_ok is not True:
        raise StructuredOutputError("review model-level ok must be true when present")
    verdict_value = normalized.get("verdict")
    verdict_reason = ""
    if isinstance(verdict_value, Mapping):
        verdict_reason = str(
            verdict_value.get("reason")
            or verdict_value.get("summary")
            or verdict_value.get("rationale")
            or ""
        ).strip()
        verdict_value = (
            verdict_value.get("decision")
            or verdict_value.get("verdict")
            or verdict_value.get("status")
        )
    verdict = _canonical_review_verdict(verdict_value)
    if verdict:
        normalized["verdict"] = verdict

    canonical_findings = normalized.get("findings")
    aliases = [
        (key, normalized.get(key))
        for key in _REVIEW_FINDING_ALIASES
        if isinstance(normalized.get(key), list) and normalized.get(key)
    ]
    if aliases and (canonical_findings is None or canonical_findings == []):
        if len(aliases) > 1 and any(value != aliases[0][1] for _, value in aliases[1:]):
            raise StructuredOutputError(
                "ambiguous review findings: multiple aliases contain different values"
            )
        canonical_findings = aliases[0][1]
        normalized["findings"] = canonical_findings
    elif aliases and isinstance(canonical_findings, list) and canonical_findings:
        if any(value != canonical_findings for _, value in aliases):
            raise StructuredOutputError(
                "contradictory review findings: canonical and alias fields differ"
            )
    for key in _REVIEW_FINDING_ALIASES:
        normalized.pop(key, None)

    if isinstance(canonical_findings, list):
        normalized["findings"] = _normalize_review_items(canonical_findings)
    observations = normalized.get("observations")
    if isinstance(observations, list):
        normalized["observations"] = _normalize_review_items(observations)
    elif observations is None:
        normalized["observations"] = []

    summary = normalized.get("summary")
    if (summary is None or not str(summary).strip()) and verdict_reason:
        normalized["summary"] = verdict_reason

    findings = normalized.get("findings")
    if verdict == "changes_required" and isinstance(findings, list) and not findings:
        raise StructuredOutputError(
            "review verdict changes_required requires at least one non-empty finding"
        )
    if verdict == "approved" and isinstance(findings, list) and findings:
        raise StructuredOutputError(
            "review verdict approved contradicts non-empty blocking findings"
        )
    return normalized


def _canonical_review_verdict(value: Any) -> str:
    normalized = str(value or "").strip().lower()
    if normalized in _APPROVED_VERDICTS:
        return "approved"
    if normalized in _CHANGES_REQUIRED_VERDICTS:
        return "changes_required"
    return normalized


def _normalize_review_items(items: Iterable[Any]) -> list[str]:
    normalized: list[str] = []
    for item in items:
        if isinstance(item, Mapping):
            text = _format_review_finding(item)
        else:
            text = str(item).strip()
        if text and text not in normalized:
            normalized.append(text)
    return normalized


def _format_review_finding(finding: Mapping[str, Any]) -> str:
    identity = str(finding.get("id") or finding.get("finding_id") or "").strip()
    severity = str(finding.get("severity") or "").strip().upper()
    repository = str(finding.get("repository") or finding.get("repo") or "").strip()
    path = str(finding.get("file") or finding.get("path") or "").strip()
    line = finding.get("line")
    location = path
    if line not in (None, ""):
        location = f"{location}:{line}" if location else f"line {line}"
    requirement = str(
        finding.get("requirement")
        or finding.get("title")
        or finding.get("message")
        or finding.get("description")
        or ""
    ).strip()
    evidence = str(finding.get("evidence") or "").strip()
    required_fix = str(
        finding.get("required_fix") or finding.get("fix") or ""
    ).strip()
    heading = " ".join(part for part in [identity, severity] if part)
    scope = "/".join(part for part in [repository, location] if part)
    parts = [part for part in [heading, scope, requirement, evidence, required_fix] if part]
    return " | ".join(parts)


def extract_structured_object(
    text: str,
    *,
    preferred_keys: Iterable[str] = (),
) -> dict[str, Any] | None:
    """Extract the most likely top-level JSON object from agent text.

    Parsing order is deterministic:

    1. exact JSON object;
    2. JSON object inside otherwise harmless text/Markdown;
    3. a single conventional wrapper object (``review``, ``result``, etc.).

    Candidate selection favours objects containing expected contract keys,
    then the widest object, then the latest occurrence. Nested evidence
    dictionaries therefore do not displace the actual response object.
    """

    stripped = str(text or "").strip()
    if not stripped:
        return None

    exact = _decode_exact_object(stripped)
    if exact is not None:
        return _unwrap_known_wrapper(exact)

    preferred = frozenset(str(key) for key in preferred_keys if str(key))
    decoder = json.JSONDecoder()
    candidates: list[tuple[int, int, dict[str, Any]]] = []

    for offset, character in enumerate(stripped):
        if character != "{":
            continue
        try:
            value, consumed = decoder.raw_decode(stripped[offset:])
        except json.JSONDecodeError:
            continue
        if isinstance(value, dict):
            candidates.append((offset, consumed, value))

    if not candidates:
        return None

    def score(candidate: tuple[int, int, dict[str, Any]]) -> tuple[int, int, int, int]:
        offset, consumed, value = candidate
        keys = set(value)
        return (
            len(keys & preferred),
            len(keys & _CONTRACT_KEYS),
            consumed,
            offset,
        )

    _, _, selected = max(candidates, key=score)
    return _unwrap_known_wrapper(selected)


def _decode_exact_object(text: str) -> dict[str, Any] | None:
    try:
        value = json.loads(text)
    except json.JSONDecodeError:
        return None
    return value if isinstance(value, dict) else None


def _unwrap_known_wrapper(payload: dict[str, Any]) -> dict[str, Any]:
    """Unwrap one conventional model-created response envelope."""

    if set(payload).intersection(_CONTRACT_KEYS):
        return payload
    for key in _WRAPPER_KEYS:
        nested = payload.get(key)
        if isinstance(nested, dict) and set(nested).intersection(_CONTRACT_KEYS):
            return dict(nested)
    return payload


def validate_structured_object(
    payload: dict[str, Any] | None,
    schema: Mapping[str, Any],
) -> list[str]:
    """Validate the JSON-schema subset used by Execraft agent contracts.

    The orchestrator intentionally avoids a runtime dependency on a full JSON
    Schema implementation. Agent contracts currently use a compact, stable
    subset: ``type``, ``required``, ``properties``, ``const``, ``enum``,
    ``minLength``, ``maxLength``, ``items``, ``minItems``, ``maxItems``,
    ``uniqueItems`` and closed/schema-valued ``additionalProperties``.
    Unknown schema keywords are ignored rather than interpreted loosely.
    """

    errors: list[str] = []
    _validate_value(payload, schema, path="$", errors=errors)
    return errors


def _validate_value(
    value: Any,
    schema: Mapping[str, Any],
    *,
    path: str,
    errors: list[str],
) -> None:
    expected_type = schema.get("type")
    if expected_type and not _matches_type(value, str(expected_type)):
        errors.append(f"{path}: expected {expected_type}, got {_type_name(value)}")
        return

    if "const" in schema and value != schema["const"]:
        errors.append(f"{path}: expected constant {schema['const']!r}")

    enum = schema.get("enum")
    if isinstance(enum, list) and value not in enum:
        errors.append(f"{path}: value {value!r} is not one of {enum!r}")

    if isinstance(value, str):
        minimum = schema.get("minLength")
        if isinstance(minimum, int) and len(value) < minimum:
            errors.append(f"{path}: string shorter than minLength={minimum}")
        maximum = schema.get("maxLength")
        if isinstance(maximum, int) and len(value) > maximum:
            errors.append(f"{path}: string longer than maxLength={maximum}")

    if isinstance(value, dict):
        required = schema.get("required") or []
        if isinstance(required, list):
            for key in required:
                if key not in value:
                    errors.append(f"{path}: missing required property {key!r}")

        properties = schema.get("properties") or {}
        if isinstance(properties, Mapping):
            for key, child_schema in properties.items():
                if key in value and isinstance(child_schema, Mapping):
                    _validate_value(
                        value[key],
                        child_schema,
                        path=f"{path}.{key}",
                        errors=errors,
                    )

        additional = schema.get("additionalProperties")
        known = set(properties) if isinstance(properties, Mapping) else set()
        if additional is False:
            for key in value:
                if key not in known:
                    errors.append(f"{path}: unexpected property {key!r}")
        elif isinstance(additional, Mapping):
            for key, child in value.items():
                if key in known:
                    continue
                _validate_value(
                    child,
                    additional,
                    path=f"{path}.{key}",
                    errors=errors,
                )

    if isinstance(value, list):
        minimum = schema.get("minItems")
        if isinstance(minimum, int) and len(value) < minimum:
            errors.append(f"{path}: array shorter than minItems={minimum}")
        maximum = schema.get("maxItems")
        if isinstance(maximum, int) and len(value) > maximum:
            errors.append(f"{path}: array longer than maxItems={maximum}")
        if schema.get("uniqueItems") is True:
            for index, item in enumerate(value):
                if any(item == previous for previous in value[:index]):
                    errors.append(f"{path}: array items are not unique")
                    break
        item_schema = schema.get("items")
        if isinstance(item_schema, Mapping):
            for index, item in enumerate(value):
                _validate_value(
                    item,
                    item_schema,
                    path=f"{path}[{index}]",
                    errors=errors,
                )


def _matches_type(value: Any, expected: str) -> bool:
    if expected == "object":
        return isinstance(value, dict)
    if expected == "array":
        return isinstance(value, list)
    if expected == "string":
        return isinstance(value, str)
    if expected == "boolean":
        return isinstance(value, bool)
    if expected == "integer":
        return isinstance(value, int) and not isinstance(value, bool)
    if expected == "number":
        return isinstance(value, (int, float)) and not isinstance(value, bool)
    if expected == "null":
        return value is None
    return True


def _type_name(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, dict):
        return "object"
    if isinstance(value, list):
        return "array"
    if isinstance(value, str):
        return "string"
    if isinstance(value, int):
        return "integer"
    if isinstance(value, float):
        return "number"
    return type(value).__name__
