"""Workspace task-git and multi-repository Git helpers."""

from execraft.workspace.task_git import (
    REPOSITORY_ID_RE,
    TASK_ID_RE,
    TASK_STATUSES,
    CheckoutStep,
    RepositorySpec,
    RepositoryState,
    TaskGitError,
    TaskManifest,
    active_task_storage_path,
    ahead_behind,
    append_handoff_git_records,
    branch_exists,
    checkout_transaction,
    clear_active_task,
    current_branch,
    ensure_git_repository,
    git,
    git_operation,
    head_commit,
    is_protected_branch,
    load_manifest,
    load_project_yaml,
    local_manifest_registry_path,
    lookup_repository,
    migrate_v1_to_v2,
    ordered_repositories,
    project_repository_path,
    project_task_directory,
    project_task_manifest_path,
    read_active_task,
    repository_root,
    repository_state,
    resolve_repository_path,
    resolve_task_id,
    run,
    select_repositories,
    shell_command,
    task_directory,
    task_manifest_path,
    utc_now,
    validate_branch_name,
    validate_manifest,
    validate_task_id,
    working_tree_dirty,
    write_active_task,
    write_manifest,
)


from execraft.workspace.lifecycle import (
    WorkspacePreparationResult,
    active_task_path,
    create_workspace_entries,
    manifest_drift,
    prepare_workspace,
    project_source_path,
    render_workspace_record,
    validate_workspace_location,
    validate_workspace_record_ownership,
)

from execraft.workspace.workspace_git import (
    WorktreeEntry,
    WorkspaceRecord,
    add_local_excludes,
    add_worktree,
    allocate_runtime,
    common_git_dir,
    compose_isolation_findings,
    default_workspace_path,
    docker_project_containers,
    load_env_file,
    load_workspace,
    migrate_task_dossier,
    parse_worktree_list,
    remove_worktree,
    run_in_workspace,
    sanitize_compose_project,
    source_status_paths,
    used_runtime_slots,
    validate_workspace_record,
    worktree_for_branch,
    workspace_registry_dir,
    workspace_registry_path,
    workspace_repository_path,
    write_env_file,
    write_workspace,
    write_workspace_marker,
)

__all__ = [
    "REPOSITORY_ID_RE", "TASK_ID_RE", "TASK_STATUSES",
    "CheckoutStep", "RepositorySpec", "RepositoryState", "TaskGitError", "TaskManifest",
    "active_task_storage_path", "ahead_behind", "append_handoff_git_records",
    "branch_exists", "checkout_transaction", "clear_active_task", "current_branch",
    "ensure_git_repository", "git", "git_operation", "head_commit",
    "is_protected_branch", "load_manifest", "load_project_yaml",
    "local_manifest_registry_path", "lookup_repository", "migrate_v1_to_v2",
    "ordered_repositories", "project_repository_path", "project_task_directory",
    "project_task_manifest_path", "read_active_task", "repository_root",
    "repository_state", "resolve_repository_path", "resolve_task_id",
    "run", "select_repositories", "shell_command",
    "task_directory", "task_manifest_path", "utc_now", "validate_branch_name",
    "validate_manifest", "validate_task_id", "working_tree_dirty",
    "write_active_task", "write_manifest",
    "WorktreeEntry", "WorkspaceRecord",
    "add_local_excludes", "add_worktree", "allocate_runtime",
    "common_git_dir", "compose_isolation_findings", "default_workspace_path",
    "docker_project_containers", "load_env_file", "load_workspace",
    "migrate_task_dossier", "parse_worktree_list", "remove_worktree",
    "run_in_workspace", "sanitize_compose_project", "source_status_paths",
    "used_runtime_slots", "validate_workspace_record", "worktree_for_branch",
    "workspace_registry_dir", "workspace_registry_path", "workspace_repository_path",
    "write_env_file", "write_workspace", "write_workspace_marker",
    "WorkspacePreparationResult", "active_task_path",
    "create_workspace_entries", "manifest_drift", "prepare_workspace",
    "project_source_path", "render_workspace_record",
    "validate_workspace_location", "validate_workspace_record_ownership",
]
