"""Shared project/task onboarding application layer."""

from .discovery import (
    BoundedFileInventory,
    DiscoveredRepo,
    DiscoveryEngine,
    DiscoveryReport,
    EcosystemDetector,
    discover,
    suggest_verification,
)
from .greenfield import (
    GreenfieldError,
    GreenfieldOutcome,
    GreenfieldService,
    GreenfieldTemplate,
    GreenfieldTemplateCatalog,
    default_greenfield_catalog,
)
from .start import (
    DraftPlanArtifact,
    DraftPlanService,
    ImportedPlanConsistencyError,
    PlannerMode,
    ProviderChoice,
    ProviderSelector,
    RepositoryScope,
    RepositorySelector,
    StartOutcome,
    StartRequest,
    StartWorkflowError,
    StartWorkflowService,
    StepStatus,
    TaskIntent,
)
from .models import (
    CreationPlan,
    Evidence,
    Finding,
    FindingSeverity,
    PlannedFile,
    ReadinessCheck,
    ReadinessReport,
    ReadinessStatus,
)
from .providers import (
    ProviderInventory,
    ProviderInventoryItem,
    ProviderInventoryReport,
)
from .readiness import ReadinessService
from .profiles import (
    FeatureDescriptor,
    ProfileCatalogError,
    ProjectProfile,
    ProjectProfileCatalog,
    ProjectProfileRenderer,
    ProjectTemplateContext,
    default_profile_catalog,
)
from .upgrades import (
    ProjectUpgradeError,
    ProjectUpgradeService,
    TemplateProvenance,
    UpgradeFile,
    UpgradePlan,
)
from .service import OnboardingOutcome, OnboardingService
from .task_definition import (
    PreparedTaskDefinition,
    TaskDefinitionError,
    TaskDefinitionInput,
    TaskDefinitionService,
)
from .templates import (
    TaskTemplateContext,
    TemplateCatalog,
    TemplateCatalogError,
    TemplateDescriptor,
)
from .transactions import (
    AtomicTreeTransaction,
    CreationResult,
    CreationTransactionError,
    ProjectCreationTransaction,
    TaskCreationTransaction,
)

__all__ = [
    "AtomicTreeTransaction",
    "BoundedFileInventory",
    "CreationPlan",
    "CreationResult",
    "CreationTransactionError",
    "DiscoveredRepo",
    "DiscoveryEngine",
    "DiscoveryReport",
    "EcosystemDetector",
    "Evidence",
    "Finding",
    "FindingSeverity",
    "FeatureDescriptor",
    "ProfileCatalogError",
    "ProjectProfile",
    "ProjectProfileCatalog",
    "ProjectProfileRenderer",
    "ProjectTemplateContext",
    "ProjectUpgradeError",
    "ProjectUpgradeService",
    "TemplateProvenance",
    "UpgradeFile",
    "UpgradePlan",
    "default_profile_catalog",
    "OnboardingOutcome",
    "OnboardingService",
    "PlannedFile",
    "ProjectCreationTransaction",
    "ProviderInventory",
    "ProviderInventoryItem",
    "ProviderInventoryReport",
    "ReadinessCheck",
    "ReadinessReport",
    "ReadinessService",
    "ReadinessStatus",
    "TaskCreationTransaction",
    "PreparedTaskDefinition",
    "TaskDefinitionError",
    "TaskDefinitionInput",
    "TaskDefinitionService",
    "TaskTemplateContext",
    "TemplateCatalog",
    "TemplateCatalogError",
    "TemplateDescriptor",
    "discover",
    "suggest_verification",
    "DraftPlanArtifact",
    "DraftPlanService",
    "GreenfieldError",
    "GreenfieldOutcome",
    "GreenfieldService",
    "GreenfieldTemplate",
    "GreenfieldTemplateCatalog",
    "ImportedPlanConsistencyError",
    "PlannerMode",
    "ProviderChoice",
    "ProviderSelector",
    "RepositoryScope",
    "RepositorySelector",
    "StartOutcome",
    "StartRequest",
    "StartWorkflowError",
    "StartWorkflowService",
    "StepStatus",
    "TaskIntent",
    "default_greenfield_catalog",
]
